---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: oh-my-zsh, tags: ['oh-my-zsh'] }
    - { role: asdf, tags: ['asdf'] }
    - { role: docker, tags: ['docker'] }
    - { role: ubuntu-make, tags: ['ubuntu-make'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: insomnia, tags: ['insomnia'] }
    - { role: messaging, tags: ['messaging'] }
    - { role: editors, tags: ['editors'] }
    - { role: kubernetes, tags: ['kubernetes'] }
    # TODO: Configure the compose key
    # TODO: install the nerd font
    # TODO: install starship
    # TODO: disable the Super+p shortcut